Repository Meet-Coder-Study/reference-documentation-study, pull requests merged in 2021-06, with the labels that each got.

#78 [A팀][김보배] Working with NoSQL Technologies_Spring Integration
  spirng-boot-2.4.x/week9/[A팀][김보배] Working_with_NoSQL_Technologies_Spring_Integration.pdf
Labels: 9주차

#77 [A팀][박기진] Working with NoSQL Technologies
  spirng-boot-2.4.x/week9/A팀_Working with NoSQL Technologies_박기진.md
Labels: 9주차

#76 [B팀][박유진] Working with NoSQL Technologies
  week9/B팀_박유진_Working_with_NoSQL_Technologies.md
  week9/image/B팀_박유진_2PhaseLockingProtocol.png
  week9/image/B팀_박유진_NoSQL예제.jpg
  week9/image/B팀_박유진_RDB예제.jpg
Labels: 9주차

#75 [B팀][박창원] Working with NoSQL Technologies
  week9/images/image-nosql-1.png
  week9/박창원_Spring_Boot_Features4.md
Labels: 9주차

#80 Feature/10week
  week10/[A팀]박기진-spring-boot-10weeks.md
  week8/A팀_유효정_Working_with_SQL_Databases.pdf
Labels: 10주차

#85 [A팀][김광훈] Deploying Spring Boot Applications
  spirng-boot-2.4.x/week12/A팀_김광훈_Deploying_Spring_Boot_Applications.md
Labels: 12주차, spring-boot-2.4.x

#87 [B팀][박은진] Container Images
  spirng-boot-2.4.x/week12/B팀_박은진_Container_Images.md
  week8/.DS_Store
Labels: 12주차, spring-boot-2.4.x

#88 [A팀][김보배] Building container images
  spirng-boot-2.4.x/week12/Building_container_image.pdf
Labels: 12주차, spring-boot-2.4.x

#86 [B팀][박유진] Creating Your Own Auto-configuration
  week11/B팀_박유진_Testing.md
  week12/B팀_박유진_Creating_Your_Own_Auto-configuration.md
Labels: 12주차, spring-boot-2.4.x
